### ISSUE TITLE
countries languages (en-US) should not be an obstacle as last resort

### ISSUE THREAD

**Issue by josenobile** [ptlis/conneg#5]
The full list: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

For example: es-419 is for Latin American Spanish and es-ES for Spanish in Spain

If I have: "es-CO" Spanish in Colombia and "es" general Spanish. For user that sends es-419 I want es-CO as language, if user sends es-ES, the language would be es.

Or only omit the part after dash when matching.

**Comment by ptlis** [comment]
Thanks for the bug report :thumbsup:

When I was building v3 of the library I spent some time considering the (technically) correct way of handling languages & tags (as described in http://www.w3.org/International/articles/language-tags/). I decided to leave it with the current naïve solution so that I could tag a stable release (as all other functionality was complete).

It would be preferable if I could avoid the work of baking in fully correct support, at least until someone has a use-case for the level of additional complexity that would be required. However as you've pointed out there should be a nicer half-way house.

I'd rather not do partial matching of languages across the board as it could break use-cases that rely on simplistic matching. To that end I would propose that allowing partial wildcard matching for tags (with a lower match precedence than exact matches) would fulfil your requirements.

For example your application preferences could be provided like ```es-*;q=0.75``` which would match any Spanish variants (es, es-ES, es-CO and so forth).

As a bonus, this scheme would also support the use-case of having a catch-all variant (e.g. es-ES) along with variants localised to the extlang tag. For example, by providing the application preferences ```es-*;q=0.75, es-ES;q=1, es-CO;q=1``` you would be saying that your application can provide localised variants for es-ES and es-CO, and a 'close-enough' catch-all for all other Spanish variants.

How does this sound to you?

**Comment by josenobile** [comment]
I like these solution, the wildcard is already supported or will be?

**Comment by ptlis** [comment]
It's not currently supported, but I've been looking into what would be required to add this feature. It looks like it will be a relatively invasive change, I'll take a look at this over the weekend but I most likely won't get a chance to do any hacking on this feature until the following one.

**Comment by ptlis** [comment]
Hi @josenobile, this feature has been implemented in the master branch, could you give it a try and verify whether or not it's working as you need it to?

**Comment by josenobile** [comment]
Yes, thank you, it works me.
